endpoints:
    issuer: https://provider:5000
    authorize: /authorize
    token: /token
    userinfo: /userinfo
    jwks: /jwk
    registration: /register
    resource_server: https://resource_server:5002
    resource: /resource
    webclient: https://localhost:5001
    post_logout: /logged_out
