endpoints:
    issuer: https://localhost:5000
    authorize: /authorize
    token: /token
    userinfo: /userinfo
    jwks: /jwk
    registration: /register
    scim: /scim/v2
    resource_server: https://localhost:5002
    resource: /resource

capabilities:
    scopes_supported: 
        - openid
        - read
        - write
    response_types_supported:
        - code
        - code id_token
    response_modes_supported:
        - query
    grant_types_supported:
        - authorization_code
    claims_supported:
        - name
        - sub
        - iss
        - aud
        - iat
        - nbf
        - exp
        - scope
