endpoints:
    issuer: https://provider:5000
    authorize: /authorize
    token: /token
    userinfo: /userinfo
    jwks: /jwk
    registration: /register
    scim: /scim/v2

capabilities:
    scopes_supported: 
        - openid
        - profile
        - email
        - roles
        - read
        - write
    response_types_supported:
        - code
        - code id_token
    response_modes_supported:
        - query
        - form_post
    grant_types_supported:
        - authorization_code
        - client_credentials
        - refresh_token
    claims_supported:
        - name
        - sub
        - iss
        - aud
        - iat
        - nbf
        - exp
        - scope
